/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import trabmodelagem1.Atendente;
/**
 *
 * @author Miih Rantre
 */
public class TelaCadastroPaciente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroPaciente
     */
    String nome;
    String cpf;
    String plano;
    String nivelDeUrgencia;

    public TelaCadastroPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoCPFP = new javax.swing.JPasswordField();
        CampoNomeP = new javax.swing.JTextField();
        TCPFP = new javax.swing.JLabel();
        TNomeP = new javax.swing.JLabel();
        BotaoSalvar = new javax.swing.JButton();
        Formulario = new javax.swing.JLabel();
        CampoPlanoP = new javax.swing.JTextField();
        TPlanoP = new javax.swing.JLabel();
        CampoNUP = new javax.swing.JTextField();
        TNup = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        CampoCPFP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoCPFPKeyReleased(evt);
            }
        });
        getContentPane().add(CampoCPFP);
        CampoCPFP.setBounds(100, 140, 240, 20);

        CampoNomeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomePActionPerformed(evt);
            }
        });
        CampoNomeP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoNomePKeyReleased(evt);
            }
        });
        getContentPane().add(CampoNomeP);
        CampoNomeP.setBounds(100, 60, 240, 20);

        TCPFP.setText("CPF:");
        getContentPane().add(TCPFP);
        TCPFP.setBounds(60, 140, 23, 14);

        TNomeP.setText("Nome Completo:");
        getContentPane().add(TNomeP);
        TNomeP.setBounds(10, 60, 90, 14);

        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoSalvarMouseClicked(evt);
            }
        });
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
        BotaoSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BotaoSalvarKeyReleased(evt);
            }
        });
        getContentPane().add(BotaoSalvar);
        BotaoSalvar.setBounds(280, 270, 110, 23);

        Formulario.setText("Formulário de Paciente");
        getContentPane().add(Formulario);
        Formulario.setBounds(30, 20, 130, 14);

        CampoPlanoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPlanoPActionPerformed(evt);
            }
        });
        CampoPlanoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoPlanoPKeyReleased(evt);
            }
        });
        getContentPane().add(CampoPlanoP);
        CampoPlanoP.setBounds(100, 100, 240, 20);

        TPlanoP.setText("Plano de Saúde:");
        getContentPane().add(TPlanoP);
        TPlanoP.setBounds(10, 100, 90, 14);

        CampoNUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNUPActionPerformed(evt);
            }
        });
        CampoNUP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoNUPKeyReleased(evt);
            }
        });
        getContentPane().add(CampoNUP);
        CampoNUP.setBounds(100, 170, 240, 20);

        TNup.setText("Nivel de Urgencia:");
        getContentPane().add(TNup);
        TNup.setBounds(10, 170, 90, 14);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(-200, -120, 620, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoCPFPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoCPFPKeyReleased
        cpf = CampoCPFP.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCPFPKeyReleased

    private void CampoNomePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomePActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomePActionPerformed

    private void CampoNomePKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoNomePKeyReleased

        nome = CampoNomeP.getText();      // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomePKeyReleased

    private void BotaoSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSalvarMouseClicked
        // TODO add your handling code here:

        Atendente at = new Atendente();
         
        int i = Integer.parseInt(nivelDeUrgencia);
        at.cadastrarPaciente(nome, cpf, i, plano);

        

    }//GEN-LAST:event_BotaoSalvarMouseClicked

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void BotaoSalvarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotaoSalvarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoSalvarKeyReleased

    private void CampoPlanoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPlanoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPlanoPActionPerformed

    private void CampoPlanoPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoPlanoPKeyReleased
        plano = CampoPlanoP.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPlanoPKeyReleased

    private void CampoNUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNUPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNUPActionPerformed

    private void CampoNUPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoNUPKeyReleased
 nivelDeUrgencia = CampoNUP.getText();         // TODO add your handling code here:
    }//GEN-LAST:event_CampoNUPKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JPasswordField CampoCPFP;
    private javax.swing.JTextField CampoNUP;
    private javax.swing.JTextField CampoNomeP;
    private javax.swing.JTextField CampoPlanoP;
    private javax.swing.JLabel Formulario;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel TCPFP;
    private javax.swing.JLabel TNomeP;
    private javax.swing.JLabel TNup;
    private javax.swing.JLabel TPlanoP;
    // End of variables declaration//GEN-END:variables
}
